name       : qt5-translations
version    : 5.6.2
release    : 23
source     :
    - http://download.qt.io/official_releases/qt/5.6/5.6.2/submodules/qttranslations-opensource-src-5.6.2.tar.xz : 7d793b447c1673206e0c5512883ad1435554dbaebf2152475b6d4a7ba6efa421
license    :
    - GPL-3.0
    - LGPL-2.1
    - LGPL-3.0
component  : desktop.qt
summary    : Qt5 Translation Components
description: |
    Translations Module for Qt5
builddeps  :
    - pkgconfig(Qt5UiTools)
setup      : |
    %qmake CONFIG+=release qttranslations.pro
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
