name       : qt5-translations
version    : 5.15.1
release    : 40
source     :
    - https://download.qt.io/official_releases/qt/5.15/5.15.1/submodules/qttranslations-everywhere-src-5.15.1.tar.xz : 46e0c0e3a511fbcc803a4146204062e47f6ed43b34d98a3c27372a03b8746bd8
homepage   : https://www.qt.io
license    :
    - GPL-3.0-or-later
    - LGPL-2.1-or-later
    - LGPL-3.0-or-later
component  : desktop.qt
summary    : Qt5 Translation Components
description: |
    Translations Module for Qt5
builddeps  :
    - pkgconfig(Qt5UiTools)
setup      : |
    %qmake CONFIG+=release qttranslations.pro
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
