name       : qt5-translations
version    : 5.15.7
release    : 48
source     :
    - git|https://invent.kde.org/qt/qt/qttranslations.git : c38edd3a5501bcd53132e1e4abb7d25a98e0e1a9
homepage   : https://www.qt.io
license    :
    - GPL-3.0-or-later
    - LGPL-2.1-or-later
    - LGPL-3.0-or-later
component  :
    - desktop.qt
    - demos : programming.library
summary    : Qt5 Translation Components
description: |
    Translations Module for Qt5
builddeps  :
    - pkgconfig(Qt5UiTools)
setup      : |
    %qmake CONFIG+=release qttranslations.pro
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
