name       : qt5-translations
version    : 5.13.0
release    : 36
source     :
    - https://download.qt.io/official_releases/qt/5.13/5.13.0/submodules/qttranslations-everywhere-src-5.13.0.tar.xz : 2f8fb3b2c62fcf1aacd0b32432b960a83546384688c0ea78514e4cf4f2f94c28
license    :
    - GPL-3.0
    - LGPL-2.1
    - LGPL-3.0
component  : desktop.qt
summary    : Qt5 Translation Components
description: |
    Translations Module for Qt5
builddeps  :
    - pkgconfig(Qt5UiTools)
setup      : |
    %qmake CONFIG+=release qttranslations.pro
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
