name       : qt5-translations
version    : 5.14.2
release    : 39
source     :
    - https://download.qt.io/official_releases/qt/5.14/5.14.2/submodules/qttranslations-everywhere-src-5.14.2.tar.xz : 2088ebee9f5dd0336c9fd11436899a95b7ce0141ce072290de1e8f315d82d1a6
homepage   : https://www.qt.io
license    :
    - GPL-3.0-or-later
    - LGPL-2.1-or-later
    - LGPL-3.0-or-later
component  : desktop.qt
summary    : Qt5 Translation Components
description: |
    Translations Module for Qt5
builddeps  :
    - pkgconfig(Qt5UiTools)
setup      : |
    %qmake CONFIG+=release qttranslations.pro
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
