name       : qt5-translations
version    : 5.10.0
release    : 29
source     :
    - https://download.qt.io/official_releases/qt/5.10/5.10.0/submodules/qttranslations-everywhere-src-5.10.0.tar.xz : ec4dbd3601afe06d1814f4bc81af9cffbbe7de2b9f4aef4eb4595b049c8eb9be
license    :
    - GPL-3.0
    - LGPL-2.1
    - LGPL-3.0
component  : desktop.qt
summary    : Qt5 Translation Components
description: |
    Translations Module for Qt5
builddeps  :
    - pkgconfig(Qt5UiTools)
setup      : |
    %qmake CONFIG+=release qttranslations.pro
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
