name       : qt5-translations
version    : 5.13.2
release    : 38
source     :
    - https://download.qt.io/official_releases/qt/5.13/5.13.2/submodules/qttranslations-everywhere-src-5.13.2.tar.xz : 25755941a2525de2d7ae48e0011d04db7cc09e4e73fe83293206ceafa0aa82d9
homepage   : https://www.qt.io
license    :
    - GPL-3.0
    - LGPL-2.1
    - LGPL-3.0
component  : desktop.qt
summary    : Qt5 Translation Components
description: |
    Translations Module for Qt5
builddeps  :
    - pkgconfig(Qt5UiTools)
setup      : |
    %qmake CONFIG+=release qttranslations.pro
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
