name       : qt5-translations
version    : 5.15.10
release    : 51
source     :
    - git|https://invent.kde.org/qt/qt/qttranslations.git : a680686754d84b91d4cc4252a2fb8af0c58f5f49
homepage   : https://www.qt.io
license    :
    - GPL-3.0-or-later
    - LGPL-2.1-or-later
    - LGPL-3.0-or-later
component  :
    - desktop.qt
    - demos : programming.library
summary    : Qt5 Translation Components
description: |
    Translations Module for Qt5
builddeps  :
    - pkgconfig(Qt5UiTools)
setup      : |
    %qmake CONFIG+=release qttranslations.pro
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
