name       : qt5-translations
version    : 5.12.2
release    : 34
source     :
    - https://download.qt.io/official_releases/qt/5.12/5.12.2/submodules/qttranslations-everywhere-src-5.12.2.tar.xz : bbe47b3995be8528ee5e78eae263a5ec224cd18e588219191716a17802e60c7b
license    :
    - GPL-3.0
    - LGPL-2.1
    - LGPL-3.0
component  : desktop.qt
summary    : Qt5 Translation Components
description: |
    Translations Module for Qt5
builddeps  :
    - pkgconfig(Qt5UiTools)
setup      : |
    %qmake CONFIG+=release qttranslations.pro
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
