name       : qt5-translations
version    : 5.11.0
release    : 30
source     :
    - http://qt.mirror.constant.com/official_releases/qt/5.11/5.11.0/submodules/qttranslations-everywhere-src-5.11.0.tar.xz : f13e92fce935ccc0e4bfd088645bf78ebadb42d4e944fc36c9dc08d537f2e81c
license    :
    - GPL-3.0
    - LGPL-2.1
    - LGPL-3.0
component  : desktop.qt
summary    : Qt5 Translation Components
description: |
    Translations Module for Qt5
builddeps  :
    - pkgconfig(Qt5UiTools)
setup      : |
    %qmake CONFIG+=release qttranslations.pro
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
