name       : qt5-translations
version    : 5.11.2
release    : 32
source     :
    - https://download.qt.io/official_releases/qt/5.11/5.11.2/submodules/qttranslations-everywhere-src-5.11.2.tar.xz : cec1a83757e9c776f6c65020bf8963e9d2037963e5a93531e6274442128d034b
license    :
    - GPL-3.0
    - LGPL-2.1
    - LGPL-3.0
component  : desktop.qt
summary    : Qt5 Translation Components
description: |
    Translations Module for Qt5
builddeps  :
    - pkgconfig(Qt5UiTools)
setup      : |
    %qmake CONFIG+=release qttranslations.pro
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
